#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Scaffold a new page with this site's shared boilerplate.

    python tools/new-page.py <slug> "<Title>" "<Heading>" "<Lead sentence>"
                             [--eyebrow "Legal"] [--crumb "Privacy"] [--noindex]

The site has no build step and no templating layer: every page carries its own
head, navbar mount, hero and footer. That is fine for a dozen pages and a
liability at twenty — the stylesheet list, the favicon set and the module entry
point are identical on all of them, and a page hand-copied from its neighbour
is a page that silently misses the next change to any of those.

So the boilerplate lives here once. The page this writes is a normal file
afterwards: edit it freely, it is never regenerated. Only the JSON-LD block is
machine-owned, and build-seo.py rewrites that on every page anyway.

After adding a page, add it to PAGES in tools/build-seo.py and re-run that, or
it will be missing from sitemap.xml and carry no structured data.
"""
import io, os, sys, argparse

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SITE = 'https://www.globalgrowthindustries.com'

TEMPLATE = '''<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

<title>{title}</title>
<meta name="description" content="{description}">
<link rel="canonical" href="{site}/{slug}">
{robots}
<link rel="preload" href="assets/fonts/inter-tight-var-latin.woff2" as="font" type="font/woff2" crossorigin>
<link rel="preload" href="assets/fonts/inter-var-latin.woff2" as="font" type="font/woff2" crossorigin>

<link rel="stylesheet" href="assets/css/tokens.css">
<link rel="stylesheet" href="assets/vendor/bootstrap/bootstrap.min.css">
<link rel="stylesheet" href="assets/css/bootstrap-overrides.css">
<link rel="stylesheet" href="assets/css/base.css">
<link rel="stylesheet" href="assets/css/components.css">
<link rel="stylesheet" href="assets/css/sections.css">
<link rel="stylesheet" href="assets/css/animations.css">
<link rel="stylesheet" href="assets/css/pages.css">

<link rel="icon" href="assets/icons/favicon/favicon.ico" sizes="32x32">
<link rel="icon" href="assets/images/logo/global-growth-mark.png" type="image/png" sizes="160x160">
<link rel="apple-touch-icon" href="assets/icons/favicon/icon-180.png">
<link rel="manifest" href="assets/icons/favicon/site.webmanifest">
<meta name="theme-color" content="#04182F">
<!-- JSON-LD: generated by scripts, derived from the site data. Do not hand-edit. -->
</head>

<body class="page-{slug}" data-page="{slug}" data-cursor>

<a class="gg-skip-link" href="#main">Skip to content</a>

<div class="gg-progress" data-progress-bar aria-hidden="true">
  <span class="gg-progress__fill"></span>
</div>

<header class="gg-nav" data-navbar></header>

<main id="main">

  <section class="gg-page-hero gg-dark" aria-labelledby="page-title">
    <div class="gg-mesh gg-page-hero__mesh" aria-hidden="true">
      <span class="gg-mesh__blob gg-mesh__blob--1"></span>
      <span class="gg-mesh__blob gg-mesh__blob--4"></span>
    </div>
    <div class="gg-container">
      <div class="gg-page-hero__inner">
        <nav class="gg-crumbs" aria-label="Breadcrumb">
          <a href="index.html">Home</a>
          <svg class="gg-icon" aria-hidden="true" focusable="false"><use href="#i-chevron-right"></use></svg>
          <a href="legal.html">Legal</a>
          <svg class="gg-icon" aria-hidden="true" focusable="false"><use href="#i-chevron-right"></use></svg>
          <span aria-current="page">{crumb}</span>
        </nav>
        <p class="gg-eyebrow">{eyebrow}</p>
        <h1 id="page-title" class="gg-h1 gg-page-hero__title">{heading}</h1>
        <p class="gg-lead gg-page-hero__lead">
          {lead}
        </p>
      </div>
    </div>
  </section>

  <section class="gg-section gg-section--white">
    <div class="gg-container gg-container--narrow">
{body}
    </div>
  </section>

</main>

<footer class="gg-footer" data-footer></footer>

<button type="button" class="gg-to-top" data-to-top aria-label="Back to top">
  <svg class="gg-icon" aria-hidden="true" focusable="false"><use href="#i-arrow-up"></use></svg>
</button>

<script type="module" src="assets/js/main.js"></script>
</body>
</html>
'''

NOINDEX = '<meta name="robots" content="noindex, follow">\n'


def build(slug, title, heading, lead, description=None, eyebrow='Legal',
          crumb=None, noindex=False, body=''):
    return TEMPLATE.format(
        slug=slug, site=SITE,
        title=title,
        description=description or lead,
        robots=NOINDEX if noindex else '',
        eyebrow=eyebrow,
        crumb=crumb or heading,
        heading=heading,
        lead=lead,
        body=body or '      <div data-page-body></div>')


def main():
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument('slug', help='file name without .html, e.g. "privacy"')
    p.add_argument('title', help='<title> text')
    p.add_argument('heading', help='the <h1>')
    p.add_argument('lead', help='one sentence under the heading')
    p.add_argument('--description', help='meta description (defaults to the lead)')
    p.add_argument('--eyebrow', default='Legal')
    p.add_argument('--crumb', help='breadcrumb label (defaults to the heading)')
    p.add_argument('--noindex', action='store_true')
    p.add_argument('--force', action='store_true', help='overwrite an existing page')
    args = p.parse_args()

    path = os.path.join(ROOT, args.slug + '.html')
    if os.path.exists(path) and not args.force:
        raise SystemExit('%s already exists — pass --force to overwrite' % args.slug)

    io.open(path, 'w', encoding='utf-8', newline='\n').write(build(
        args.slug, args.title, args.heading, args.lead,
        args.description, args.eyebrow, args.crumb, args.noindex))
    print('wrote %s.html' % args.slug)
    print('next: add it to PAGES in tools/build-seo.py, then re-run that script')


if __name__ == '__main__':
    main()
